### PR TITLE
ENH: Add website build workflow status badge to `README`

### PR DESCRIPTION
**Pull request by jhlegarreta**
Add website build workflow status badge to `README`.

### CODE REVIEW

**Comment by jhlegarreta** [comment]
Not sure why no status is being reported;  have tried creating the badge with different branches in the workflow itself to no avail. The badge is being displayed correctly in the `lesson-example`. Might have to do with https://github.com/carpentries/styles/issues/581.

**Comment by josephmje** [comment]
> Not sure why no status is being reported; have tried creating the badge with different branches in the workflow itself to no avail. The badge is being displayed correctly in the `lesson-example`. Might have to do with [carpentries/styles#581](https://github.com/carpentries/styles/issues/581).

I think we want to display the status of the build-test workflow instead of the website workflow?

**Comment by jhlegarreta** [comment]
> I think we want to display the status of the build-test workflow instead of the website workflow?

The build-test is already being displayed. The `website` check reflects the website build status (i.e. whether the markdown files can be process to be rendered, whether they stick to the carpentries style, etc.).

**Comment by josephmje** [comment]
> > I think we want to display the status of the build-test workflow instead of the website workflow?
> 
> The build-test is already being displayed. The `website` check reflects the website build status (i.e. whether the markdown files can be process to be rendered, whether they stick to the carpentries style, etc.).

My mistake!

**Review by kaitj — COMMENTED** [review]
This looks fine to me with regards to adding the badge.

Regarding the `No status`, could it be similar to this: https://github.community/t/workflow-badge-always-no-status-when-limited-to-branch-master/17087? 

Also from what I can tell, the `Build, test` status badge has only tested off this repo in recent runs - can't recall if the badge displayed correctly before. Similarly, last few workflow runs in `lesson-example` has also been on the main repo. Might be something along the lines of trying to query an actions workflow triggered by a branch on a fork? 

I'd be okay with merging this in, seeing what happens and opening a separate PR if changes are needed.

**Review by kaitj — APPROVED** [review]

**Comment by jhlegarreta** [comment]
> Regarding the `No status`, could it be similar to this: https://github.community/t/workflow-badge-always-no-status-when-limited-to-branch-master/17087?

We are not limiting the badge to the master branch, which OTOH I think we should (my bad) and should in any case not be an issue.

> Also from what I can tell, the` Build, test` status badge has only tested off this repo in recent runs - can't recall if the badge displayed correctly before.

It has always displayed the expected status.

> Similarly, last few workflow runs in `lesson-example` has also been on the main repo. Might be something along the lines of trying to query an actions workflow triggered by a branch on a fork?

I'd say that it does not have to do with that. Inspecting more closely the workflow file, turns out that only `gh-pages` and `main` branches get tested when pushing, which we do not have. But `gh-pages` is created within the workflow and thus the workflow is run, but then no status is reported I guess. So maybe we should at least switch our `master` to `main`.

**Pull request merged**
