### PR TITLE
BUG: Fix probabilistic tractography notebook

### PR DESCRIPTION
**Pull request by jhlegarreta**
Fix probabilistic tractography notebook: the Jupyter engine was unable to parse
the notebook since it was missing some newline/end of line characters (`,`), and
thus did not constitute a valid JSON entity.

### CODE REVIEW

**Comment by jhlegarreta** [comment]
A few notes:
- Not sure when this stopped working or when the changes were introduced.
- I tried to launch the notebook using `binder` but looks like the latest changes (including this notebook) are not available. We may want to update that.

**Comment by kaitj** [comment]
> I tried to launch the notebook using binder but looks like the latest changes (including this notebook) are not available. We may want to update that.

Yeah, I've been thinking we may want to update the binder link all together to use this repo (I think it currently points to @josephmje's repo). We can probably open a separate issue for this!

**Review by kaitj — APPROVED** [review]

**Comment by jhlegarreta** [comment]
> We can probably open a separate issue for this!

Sure.

**Comment by kaitj** [comment]
> Not sure when this stopped working or when the changes were introduced. Maybe you can try locally on the master branch to confirm that an issue exists.

Confirmed not working on master. 

Locally, automatic execution of probabilistic tractography jupyter notebook appears to be working.

**Pull request merged**
