### PR TITLE
FIX: Trim Python package requirements

### PR DESCRIPTION
**Pull request by josephmje**
Addresses #31

### CODE REVIEW

**Comment by jhlegarreta** [comment]
The change looks fair to me.

Not sure why the CIs are not being triggered, though. Not specific to this PR, since I realize that others have not triggered them; only merges to the main branch have triggered them, even thought they are set for `push` events and [should be enough](https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#example-using-a-single-event). Maybe it has to do with triggering the GitHub Actions by pushes from forked repositories.

**Review by jhlegarreta — APPROVED** [review]

**Comment by josephmje** [comment]
it looks like the install requirements step is now passing. but the test notebooks step is failing. does the path for the ipynb notebooks need to be updated?

**Comment by jhlegarreta** [comment]
> it looks like the install requirements step is now passing. but the test notebooks step is failing. does the path for the ipynb notebooks need to be updated?

OK, I see the build in your fork. Probably the search pattern I put was relative the current directory and it should be adjusted. We could address that in a separate PR, and have this merged to make things go forward (and since in any case the downloading the data is a step that still requires to be added to the CI pipeline).

**Comment by josephmje** [comment]
Sounds good! I'll merge this is and the CI pipeline can be updated separately.

**Pull request merged**
