### PR TITLE
FIX: Update image display in DTI lesson

### LINKED ISSUE #78: Fix `{:class=”img-responsive”}` tags
A few `{:class=”img-responsive”}` tags exist throughout the episodes that seem not to be properly recognized (e.g. `https://carpentries-incubator.github.io/SDC-BIDS-dMRI/diffusion_tensor_imaging/index.html).

They should either be removed or fixed.

### PR DESCRIPTION
**Pull request by josephmje**
Resolves #78

### CODE REVIEW

**Comment by josephmje** [comment]
This might have not fixed the problem. It looks like all of the images display properly on the netlify build but not the actual website.

**Comment by jhlegarreta** [comment]
I think it does solve the problem; the images not being displayed in the actual website/`master` branch might be related to the `{{ base }}` vs. `{{ relative_root_path }}` choice in #71? Not sure why netlify resolves paths anyway. Maybe the site should be built locally to see if the placeholder is the culprit.

**Comment by josephmje** [comment]
> Maybe the site should be built locally to see if the placeholder is the culprit.
Will try this out and report back

**Comment by josephmje** [comment]
Looks like the local build also displays everything correctly.

**Review by jhlegarreta — APPROVED** [review]
Not sure when the exercises part got changed and if it is that what is preventing the images from being displayed.

**Comment by josephmje** [comment]
> Not sure when the exercises part got changed and if it is that what is preventing the images from being displayed.

Sorry, I should have made a separate PR to fix the exercise rendering. It's a separate issue from the images getting displayed. I'm unclear on why netlify and local builds succeed but the GitHub pages deployment fails. I haven't actually been checking the GitHub pages deployment that frequently so I'm also not sure when this issue got introduced.

**Comment by jhlegarreta** [comment]
> Sorry, I should have made a separate PR to fix the exercise rendering. It's a separate issue from the images getting displayed. I'm unclear on why netlify and local builds succeed but the GitHub pages deployment fails. I haven't actually been checking the GitHub pages deployment that frequently so I'm also not sure when this issue got introduced.

OK. No worries. Maybe sync'ing the theme had something to do also. Let's merge this and #82 (@kaitj we can leave adding the text for a separate PR) to move things forward.

**Pull request merged**
