### PR TITLE
ENH: Make the `FURY` screenshots be displayed inline

### PR DESCRIPTION
**Pull request by jhlegarreta**
Make the `FURY` screenshots be displayed inline.

### CODE REVIEW

**Comment by jhlegarreta** [comment]
Partially addressed #29.

**Review by kaitj — CHANGES_REQUESTED** [review]
Changes look good - just a few comments:

1. [Markdown] The basic equations summarizing SD: big gap between sentences, created presumably by the screenshot (doesn't necessarily need to be changed)
2. [Jupyter] The path for `t1_layout` includes an extra "33" just before `ds000221` in the first cell. (should probably be fixed).

**Comment by jhlegarreta** [comment]
Thanks for the review Jason :+1:

> 1. [Markdown] The basic equations summarizing SD: big gap between sentences, created presumably by the screenshot (doesn't necessarily need to be changed)

Seems like Jekyll is unable to build the site and I cannot check how it looks like. The [file itself](https://github.com/carpentries-incubator/SDC-BIDS-dMRI/blob/master/fig/5/spherical_deconvolution_equation.png) does not seem to have an excessive white space around vertically. Maybe an issue can be opened and an screenshot added so that we can keep track of it separately?

> 2. [Jupyter] The path for t1_layout includes an extra "33" just before ds000221 in the first cell. (should probably be fixed).

Addressed in 1ffab3f.

**Comment by josephmje** [comment]
> Seems like Jekyll is unable to build the site and I cannot check how it looks like. The [file itself](https://github.com/carpentries-incubator/SDC-BIDS-dMRI/blob/master/fig/5/spherical_deconvolution_equation.png) does not seem to have an excessive white space around vertically. Maybe an issue can be opened and an screenshot added so that we can keep track of it separately?

There was a mismatch with some of the file paths in the instructor guide. Fixed in #43 and was able to build the website fine locally.

**Review by josephmje — APPROVED** [review]

**Comment by kaitj** [comment]
Haven't had a chance to look at the local website again, but am okay with merging given the pathing issue was addressed.

**Review by kaitj — APPROVED** [review]

**Pull request merged**
