### PR TITLE
MAINT: Refactoring of notebook 2 & convert to carpentries format

### PR DESCRIPTION
**Pull request by kaitj**
Complete revamp of notebook 2. Addition of dipy preprocessing for brainmasking. FSL topup and eddy steps added. Registration with ANTS and rotation of bvec file also included.

---

### CODE REVIEW

**Comment by kaitj** [comment]
@jhlegarreta @josephmje I've created a draft PR for now until I get a chance to finish preprocessing the data. The registration (final step) will be done once servers are back up. Good chance to take a look and make any changes before I commit the PR for review. Will make separate PR once the notebooks are converted to carpentries format.

**Comment by jhlegarreta** [comment]
@kaitj thanks for doing this. Will try to save some time during the weekend to have a look.

**Comment by kaitj** [comment]
The notebook has been updated to have the DWI volume as the reference image and the T1w volume as the moving image. Additional changes include a note mentioning if DWI is to be used as the moving image, the bvecs also have to be similarly rotated.

**Comment by jhlegarreta** [comment]
Thanks @kaitj :+1:. Have not tried locally, but I assume it is OK. Thanks for adding the note on the DWI->T1w registration !

I'd vote for merging and making further changes in separate PRs if necessary (e.g. updating the corresponding lesson Markdown file).

**Comment by kaitj** [comment]
That sounds good to me. I still need to add in a few images to the notebook, so I will do that, commit and mark this ready for review The carpentries formatting will be done on a separate branch!

**Comment by kaitj** [comment]
Marking as ready for review (will have a separate PR for the carpentries markdown formatted notebooks!)

Will note that the notebook in the solutions folder and the parent directory are the same. I have not removed any of the "solutions" so those would have to be updated prior to teaching with this set of notebooks.

**Comment by jhlegarreta** [comment]
> I have not removed any of the "solutions" so those would have to be updated prior to teaching with this set of notebooks. 

Not sure what updates are required, but an issue can be opened to keep track of it if necessary.

I do not have the rights to add anybody as a reviewer, nor do I have merge rights, but I am for merging this.

**Comment by kaitj** [comment]
Renamed the PR, and updated PR to include markdown notebooks. Still need to add exercises, but that can be done in a separate PR I think.

@jhlegarreta @josephmje - if you guys want to take another look.

**Comment by jhlegarreta** [comment]
Thanks for doing this @kaitj . I had a quick look:
- Maybe the diagram borrowed from `qsiprep` should get a proper citation if it exists, or at least linking to their website.
- Why does the T1w volume screenshot have a sort of black patch and background noise (leftmost figure in `T1w_brainmask.png`).

Other than that, in the interest of going forward, I'm for merging this, and making any further improvement, including the exercises, in separate PRs.

**Comment by kaitj** [comment]
>Maybe the diagram borrowed from qsiprep should get a proper citation if it exists, or at least linking to their website.
Agree with this, will take a look for it! I thought it was previously in there

>Why does the T1w volume screenshot have a sort of black patch and background noise 
The figure is suppose to show the before and after. Left most image is straight from the source from the second inversion. The black box I believe is for anonymization and the image is not denoised.

**Comment by jhlegarreta** [comment]
>> Maybe the diagram borrowed from qsiprep should get a proper citation if it exists, or at least linking to their website.

> Agree with this, will take a look for it! I thought it was previously in there

I'd be fine if you chose to add it at a later time (separate PR).

>> Why does the T1w volume screenshot have a sort of black patch and background noise

> The figure is suppose to show the before and after. Left most image is straight from the source from the second inversion. The black box I believe is for anonymization and the image is not denoised.

OK.

**Comment by kaitj** [comment]
Definitely, will try to add it in the coming week

**Review by jhlegarreta — APPROVED** [review]

**Review by josephmje — APPROVED** [review]

**Pull request merged**
