### PR TITLE
ENH: Re-organize lessons

### PR DESCRIPTION
**Pull request by jhlegarreta**
Re-organize lessons: re-group the local orientation reconstruction and
tractography lessons as different subsections of their topics, and provide an
overview/introduction section for them.

Update the lessons table accordingly in the `README`.

Fix the links to the lessons pages in the `README`.

Take advantage of the commit to update the `About the Lesson` section in the
`README` to match the actual contents.

### CODE REVIEW

**Comment by tobyhodges** [comment]
@jhlegarreta is this the kind of thing you are hoping to achieve?

Screenshot 2021-01-15 at 10 03 04

**Comment by jhlegarreta** [comment]
@tobyhodges yes, exactly !! Absolutely awesome :100:.

**Comment by tobyhodges** [comment]
That's good to hear 😄 I will make a Pull Request to your branch so you can merge the changes into this PR. I'll include some explanation of what I did, so you can continue to maintain it in future.

**Comment by jhlegarreta** [comment]
@josephmje @kaitj I asked the `Carpentries` team for some help to refactor the `Schedule` to be able to have some smarter sectioning. Toby Hodges took a stab at it and made the wonder you may see in [this comment](https://github.com/carpentries-incubator/SDC-BIDS-dMRI/pull/47#issuecomment-760767294). His changes have now been merged.

Although I've just realized that a further level of sectioning might be desirable for the `Local tracking`, i.e. having the `Deterministic` and `Probabilistic` lessons as its subsections, I think that is a minor detail, and since other tracking families might also have them but we may not necessarily cover all cases, I think it is good enough as long as it is made clear within the lessons contents.

I also discussed with Toby some other [potential enhancements](https://github.com/jhlegarreta/SDC-BIDS-dMRI/pull/1#issuecomment-762556306), but for the time being I'd say that this PR is ready to be merged.

**Comment by kaitj** [comment]
Changes look good to me - subsectioning definitely a good idea.

**Review by josephmje — APPROVED** [review]
wowww this is a really nice update!

**Review by kaitj — APPROVED** [review]
There should probably be some consistency with the naming of the episodes. Noticed the capitilization were different between a couple (eg. "Deterministic Tractography" vs "Probablistic tractography"). Not a big deal and can be updated later! Otherwise looks good to me.

**Comment by jhlegarreta** [comment]
> There should probably be some consistency with the naming of the episodes. Noticed the capitilization were different between a couple (eg. "Deterministic Tractography" vs "Probablistic tractography"). Not a big deal and can be updated later! Otherwise looks good to me.

I rebased the commits, fixed the inconsistencies, and push-forced. Ready to be merged.

**Pull request merged**
