### PR TITLE
DOC: Add discussion section about camera setup

### PR DESCRIPTION
**Pull request by jhlegarreta**
Add discussion section about camera setup.

### CODE REVIEW

**Comment by jhlegarreta** [comment]
Following the discussion in #69.

#76 should be merged before this.

This should probably be be cross-referenced from the episode and notebook. Not sure about the best/cleanest way to do it.

**Review by kaitj — COMMENTED** [review]
This looks good to me. The sagittal view might actually be sagittal left. Was originally suppose to be sagittal right, and I think I never changed the comment. I can try to create a figure later this week to add to this, but agreed we should figure out if the image filepath is valid.

**Comment by jhlegarreta** [comment]
> This looks good to me. The sagittal view might actually be sagittal left. Was originally suppose to be sagittal right, and I think I never changed the comment. I can try to create a figure later this week to add to this, but agreed we should figure out if the image filepath is valid.

I'd first merge #76, then do a separate PR to either change the title to sagittal left or generate a sagittal right view. But that is independent of the additions of this PR. I had similar conocerns about the coronal view being posterior (but did not had a detailed look at it): both left/right and anterior/posterior changes can be done in a separate PR if appropriate.

OK as for generating the figure as time permits.

**Comment by kaitj** [comment]
> I had similar conocerns about the coronal view being posterior (but did not had a detailed look at it)

Yeah, I realized I never had a chance to double check orientations. I'll put it on my to do list!

**Comment by kaitj** [comment]
Leaving this here more as a note for now so its not forgotten / can be double checked. 
Looks like two views that need to be changed are:
* Sagittal right -> Sagittal left
* Coronal anterior -> Coronal posterior

**Review by kaitj — APPROVED** [review]

**Pull request merged**
