### PR TITLE
Automate requirement updates check with dependabot

### PR DESCRIPTION
**Pull request by georgebisbas**
This PR automates the generation of PRs related to the version of requirements using the
https://github.com/dependabot/dependabot-core
dependabot package

### CODE REVIEW

**Review by jhlegarreta — CHANGES_REQUESTED** [review]
@georgebisbas thanks for proposing this.

The GitHub Actions Python setup were already proposed in PR #224; please remove them from this PR.

Checking for new Python package versions daily seems excessive. I am also hesitant to bump new versions as right now we are unable to have a CI working to test or run our notebooks.

You also put yourself as the assignee: are you planing to become involve in the maintenance of the repository?

Add a new EOF line at the end of the YAML file in case we decide this is something we want to have.

**Comment by georgebisbas** [comment]
> @georgebisbas thanks for proposing this.
> 
> The GitHub Actions Python setup were already proposed in PR #224; please remove them from this PR.
> 
> Checking for new Python package versions daily seems excessive. I am also hesitant to bump new versions as right now we are unable to have a CI working to test or run our notebooks.
> 
> You also put yourself as the assignee: are you planing to become involve in the maintenance of the repository?
> 
> Add a new EOF line at the end of the YAML file in case we decide this is something we want to have.

Hi @jhlegarreta, could I get more info on why CI is not working?
I would be happy to keep an eye on dependabot assuming CI is reinstated

**Comment by jhlegarreta** [comment]
> Hi @jhlegarreta, could I get more info on why CI is not working?

The issue is that the CI time outs while trying to install FSL, e.g.:
https://github.com/carpentries-incubator/SDC-BIDS-dMRI/actions/runs/5326231968/jobs/9647991156#step:7:37

It has been some months since it has been timing out. It used to work fine. I have not figured out why it is timing out. Suggestions/fixes for this are more than welcome.

**Comment by jhlegarreta** [comment]
@georgebisbas I am closing this for the reasons stated above. The CI is working now, although some tests timeout (PRs #205, #207, #208 need to be revisited to see if we can avoid timeouts). I still believe that opening PRs automatically for new versions of packages daily is not something desirable; maybe a better thing would be to test the notebooks weekly with the latest packages.

**Pull request closed without merging**
